### PR TITLE
Update GN bootstrap script in adapt to changes in //base/message_loop.

### PR DESCRIPTION
**Pull request by hujiajie**

### CODE REVIEW

**Comment by rogerwang** [comment]
You didn't say why do we need this.

**Comment by hujiajie** [comment]
I've updated the commit message. Please take a look.

**Comment by rogerwang** [comment]
Building GN shouldn't include message_pump_uv.cc, should it?

**Comment by hujiajie** [comment]
GN depends on //base, so message_pump_uv.cc must be pulled in to avoid undefined symbols during linking, though it's not used at runtime.

**Comment by rogerwang** [comment]
This is only a workaround and not correct fix in root cause. Building GN shouldn't include any code we've done for Node.js integration.

**Comment by hujiajie** [comment]
Seems there's some divergence : (
but I just view _uv as an oridnary message pump backend in //base, so I choose to follow the way how other backends like _default, _libevent, _win, _mac are handled.

**Pull request closed without merging**
