### PR TITLE
Enhance chrome.app.window API with window background color

### PR DESCRIPTION
**Pull request by fujunwei**
The default background color of window is white, a flash of white
will be shown if the loaded page uses a dark background. So add a new
property named background_color to CreateWindowOptions that can be configured
the same as page dark background instead of white default color.

BUG=https://github.com/nwjs/nw.js/issues/5502

### CODE REVIEW

**Comment by fujunwei** [comment]
@rogerwang PTAL, thanks.

**Comment by rogerwang** [comment]
btw, you might be interested in this: https://codereview.chromium.org/2733093002

**Comment by fujunwei** [comment]
I will send the first started white flash to chromium upstream at the same time. Thanks.

**Comment by rogerwang** [comment]
please rebase

**Comment by halton** [comment]
@fujunwei I guess you finish the rebase, is ready for @rogerwang'sreview?

**Comment by fujunwei** [comment]
Yes, it's ready. @rogerwang do you have other comments?

**Comment by rogerwang** [comment]
In our previous meeting in May, we talked about a patch you submitted to upstream for this feature. I asked for the link to be posted in this PR so I can check upstream's comments. And you didn't answer my question in another PR you submitted 2 weeks ago with the same title: https://github.com/nwjs/chromium.src/pull/82#issuecomment-303903080

**Comment by fujunwei** [comment]
> In our previous meeting in May, we talked about a patch you submitted to upstream for this feature. I asked for the link to be posted in this PR so I can check upstream's comments.

https://codereview.chromium.org/2738373002 is propose to enhance chrome.app.window API with an option of background color, but app approver considers it’s not necessary to a background color property that discusses in https://groups.google.com/a/chromium.org/forum/?utm_medium=email&utm_source=footer#!msg/chromium-dev/xkZX6YhBuJo/Vt-iwy1lBAAJ.

so i sent another cl to fix https://bugs.chromium.org/p/chromium/issues/detail?id=470669 that is a white flash in the content area while the NTP waits to load/paint. CL is https://codereview.chromium.org/2820753005, but the issue was resolved by someone's CL. 

but cl https://codereview.chromium.org/2820753005 is going on discussing with upstream.

> And  you didn't answer my question in another PR you submitted 2 weeks ago with the same title: #82 (comment)

I saw you have closed #82 that is based on nw22, so i didn't continue to give comments.

**Comment by rogerwang** [comment]
So why did you launch another PR while this one is open and under review? Are they with same code? Which one should I review?

**Comment by fujunwei** [comment]
Please continue reviewing this PR that base on nw21.

**Comment by ParticleCore** [comment]
Is there any progress on this option? (Adding the ability to set the default browser background color) It's been two years.

**Comment by fujunwei** [comment]
It's unnecessary no longer.

**Comment by ParticleCore** [comment]
@fujunwei I cannot see it in the documentation, has it been implemented in a different way? Because it is still showing a white flash when the app is launched before any CSS/HTML has a chance to load. This is on a Windows 10 running the nwjs-sdk-v0.37.1-win-x64

**Comment by lst1975** [comment]
1.
in the file package.json
{
   window: {
     show: false,
   }
}

2. <body style="background-color:xxxx">

3. when index.html loaded, run the following code. 
  {
    // Get the current window
    var gui = require('nw.gui');
    // Get the current window
    var win = gui.Window.get();
    win.show();
  };

**Comment by lst1975** [comment]
first, in the file package.json, window: { show: false }
second, <code><body style='background-color:xxx'></code>
finally, when index.html loaded, run the following code
require('nw.gui').Window.get().show;

**Comment by lst1975** [comment]
first, in the file package.json, window: { show: false }
second, body &lt;style='background-color:xxx'&gt;
finally, when index.html loaded, run the following code
require('nw.gui').Window.get().show;

**Comment by ParticleCore** [comment]
@lst1975 That is not a solution for the problem, it is a workaround that has been in use since this issue was first brought to their attention. This will cause the app to appear to be "stuck" or lag whenever it is opened, it is not a good experience to the user, you have to remember to do that for every single window you create and if it isn't a window with `nw` context you cannot do this at all.

**Comment by lst1975** [comment]
YES. I see. I just find it is better for starting my app. If the app opened quickly, the white screen will not stay too long.
Thank you very much. My app is based on nw. www.peakgmt.com. It realy a unplansant experience, because my app use a black background.


 
---Original---

**Pull request closed without merging**
