### PR TITLE
Fix #5517: window.open not aware the parameters height and width

### PR DESCRIPTION
**Pull request by xzhan96**
#5517

### CODE REVIEW

**Comment by xzhan96** [comment]
@rogerwang please help to review and merge.
[#5517](https://github.com/nwjs/nw.js/issues/5517)

**Comment by rogerwang** [comment]
merged into the master patch. thanks.

**Comment by rogerwang** [comment]
The case ' issue4221-win-open-manifest' failed with this patch. Please check it asap.

**Comment by xzhan96** [comment]
@rogerwang how to check?

**Comment by rogerwang** [comment]
You should run the sanity test cases as described in the doc: http://docs.nwjs.io/en/latest/For%20Developers/Writing%20Test%20Cases%20for%20NW.js/

I'll revert the patch for now if there is no new patch for this today.

**Comment by rogerwang** [comment]
To run a single case, simple set the environment variable `CHROMEDRIVER` to the full path of chromedriver executable in the build output directory and set `PYTHONPATH` to the full path of `src/third_party/webdriver/pylib/`

**Comment by xzhan96** [comment]
@rogerwang the patch is correct. The issue is in the test case.
Before the patch, the new window created by window.open will always has the same width/height with main window, and the test just check if(new window's size == main window's size), so the test can be passed.
However, that't not right, per the [description in nw doc](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#window-subfields), the width/height in package.json **is the initial width/height of the main window.**

So the test case need to be updated.

**Comment by rogerwang** [comment]
Thanks I'll check it. Please submit a PR for the case.

**Comment by xzhan96** [comment]
sure, I will submit a new PR for that.

**Comment by rogerwang** [comment]
Please update that case to cover the scenario of this bug as well.

**Comment by rogerwang** [comment]
I checked it again. According to the document, most of window subfields should be inherited by sub windows opened by window.open() or links by default, including height/width. So the test case is correct.

**Pull request closed without merging**
